preset: recommended

risky: true

linting: true

enabled:
  - strict
  - align_equals
  - newline_after_open_tag

disabled:
  - unalign_equals
  - no_empty_phpdoc

finder:
  exclude:
    - "src/Model"
    - "src/Interfaces"
